//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedivereKnx.GUI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedivereKnx.GUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Open Data File 的本地化字符串。
        /// </summary>
        internal static string Dlg_OpenDataFile {
            get {
                return ResourceManager.GetString("Dlg_OpenDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open HMI File 的本地化字符串。
        /// </summary>
        internal static string Dlg_OpenHmiFile {
            get {
                return ResourceManager.GetString("Dlg_OpenHmiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Message Log 的本地化字符串。
        /// </summary>
        internal static string Dlg_SaveMsgLog {
            get {
                return ResourceManager.GetString("Dlg_SaveMsgLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KNX routing interface local IP &apos;{0}&apos;, modify the configuration? 的本地化字符串。
        /// </summary>
        internal static string Ex_LocalIp {
            get {
                return ResourceManager.GetString("Ex_LocalIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acount Info 的本地化字符串。
        /// </summary>
        internal static string Hdr_Account {
            get {
                return ResourceManager.GetString("Hdr_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address 的本地化字符串。
        /// </summary>
        internal static string Hdr_IpAddress {
            get {
                return ResourceManager.GetString("Hdr_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Family 的本地化字符串。
        /// </summary>
        internal static string Hdr_IpFamily {
            get {
                return ResourceManager.GetString("Hdr_IpFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scene Address 的本地化字符串。
        /// </summary>
        internal static string Hdr_ScnAddress {
            get {
                return ResourceManager.GetString("Hdr_ScnAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scene Name 的本地化字符串。
        /// </summary>
        internal static string Hdr_ScnName {
            get {
                return ResourceManager.GetString("Hdr_ScnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization successful, please restart the program. 的本地化字符串。
        /// </summary>
        internal static string Info_AuthSuccess {
            get {
                return ResourceManager.GetString("Info_AuthSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string NetInterface_Down {
            get {
                return ResourceManager.GetString("NetInterface_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string NetInterface_Up {
            get {
                return ResourceManager.GetString("NetInterface_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Text_GPLv3 {
            get {
                return ResourceManager.GetString("Text_GPLv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        internal static string Ui_BtnShow {
            get {
                return ResourceManager.GetString("Ui_BtnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        internal static string Ui_RootNode {
            get {
                return ResourceManager.GetString("Ui_RootNode", resourceCulture);
            }
        }
    }
}
