//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BedivereKnx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BedivereKnx.ResString", typeof(ResString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Knx Connection State 的本地化字符串。
        /// </summary>
        internal static string DataCol_ConnState {
            get {
                return ResourceManager.GetString("DataCol_ConnState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string DataCol_Enable {
            get {
                return ResourceManager.GetString("DataCol_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network Status 的本地化字符串。
        /// </summary>
        internal static string DataCol_NetStatus {
            get {
                return ResourceManager.GetString("DataCol_NetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Reachable 的本地化字符串。
        /// </summary>
        internal static string DataCol_Reachable {
            get {
                return ResourceManager.GetString("DataCol_Reachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch Control Value 的本地化字符串。
        /// </summary>
        internal static string DataCol_SwCtlValue {
            get {
                return ResourceManager.GetString("DataCol_SwCtlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Feedback Value 的本地化字符串。
        /// </summary>
        internal static string DataCol_ValFdbValue {
            get {
                return ResourceManager.GetString("DataCol_ValFdbValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid enum value &apos;{0}&apos;. ({1}) 的本地化字符串。
        /// </summary>
        internal static string ExMsg_EnumInvalid {
            get {
                return ResourceManager.GetString("ExMsg_EnumInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid {0} file format. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_FileFormatInvalid {
            get {
                return ResourceManager.GetString("ExMsg_FileFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_FileNotFound {
            get {
                return ResourceManager.GetString("ExMsg_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t found {0} where &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KeyNotFound {
            get {
                return ResourceManager.GetString("ExMsg_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KNX datapoint type: {0}. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxDptInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxDptInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KNX interface type: {0}. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxInterfaceTypeInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxInterfaceTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KnxObjectPart: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxObjectPartInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxObjectPartInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t found ‘{0}’ group part in ‘{1}’. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxObjectPartNotFound {
            get {
                return ResourceManager.GetString("ExMsg_KnxObjectPartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KnxObjectType: {0}. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxObjectTypeInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxObjectTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KnxInterface port:{0} (code={1}). 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxPortInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxPortInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty KnxScene address where &apos;SceneCode = {0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxSceneAddressNull {
            get {
                return ResourceManager.GetString("ExMsg_KnxSceneAddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid KNX scene number:{0}. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_KnxSceneNumberInvalid {
            get {
                return ResourceManager.GetString("ExMsg_KnxSceneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can&apos;t be null ({1}). 的本地化字符串。
        /// </summary>
        internal static string ExMsg_NoNullAllowed {
            get {
                return ResourceManager.GetString("ExMsg_NoNullAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data table miss: {0}. 的本地化字符串。
        /// </summary>
        internal static string ExMsg_TableMiss {
            get {
                return ResourceManager.GetString("ExMsg_TableMiss", resourceCulture);
            }
        }
    }
}
